<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function ui_patterns_ds_theme() {
  return [
    'ui_patterns_ds' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements HOOK_preprocess_hook().
 */
function ui_patterns_ds_preprocess_field__ui_patterns_ds(&$vars) {
  $ds_config = $vars['ds-config'];
  $vars['component'] = [
    '#type' => 'component',
    '#component' => $ds_config['settings']['component_id'] ,
    '#ui_patterns' => $ds_config['settings'],
  ];
}
